### ISSUE TITLE
Incorrect timestamp on other track

### ISSUE THREAD

**Issue by TSKangetsu** [tekartik/midi.dart#28]
![image](https://github.com/tekartik/midi.dart/assets/43801783/55c469af-da1f-43d2-b4ba-b03463baed59)

channel 5,6,7 doesn't look right, about 2 seconds delay here, this only appear in multiple channel

**Comment by TSKangetsu** [comment]
![image](https://github.com/tekartik/midi.dart/assets/43801783/4768cc97-a5c1-4624-ac33-975309206504)
This mid file appears to have 2 BPM metadata，will this cause problems？

**Comment by alextekartik** [comment]
That could likely be the issue since I don't think I encounter this yet (and I think I have a single time signature per file). Would you be able to share the midi file so I can take a look?

**Comment by TSKangetsu** [comment]
[we_shall_die_together_unknown_.zip](https://github.com/tekartik/midi.dart/files/11732838/we_shall_die_together_unknown_.zip)

**Comment by alextekartik** [comment]
Indeed, it seems I need to handle the time signature slightly differently to handle this properly. I'll look into it and keep you posted

**Comment by alextekartik** [comment]
I don't see anything wrong with the file, indeed channel 6,7,8 start later. Just to understand, did you generate this file with this lib, do you have any problem playing it with a midi player or are you noticing something special I should look at?

**Comment by TSKangetsu** [comment]
I use flutter_midi_command to play it, when i remove 120bpm meta, only 140bpm, it play normally. If file has multiple bpm, some track won't play with correct time, file tracks 5、6、7  still get 120bpm timestamp
![image](https://github.com/tekartik/midi.dart/assets/43801783/8e3cf808-5c6b-4c0c-8e39-6695eb503577)

**Comment by TSKangetsu** [comment]
May be midi_file_player problem? I'm still checking the code.

**Comment by alextekartik** [comment]
Ok I think I understand, indeed midi_file_player assume a fixed time/tempo signature. I'll check how I can improve that.

**Comment by alextekartik** [comment]
Indeed the time computation in MidiFilePLayer was wrong when there was a bpm change. I think this is fixed
